version: 0.0
os: linux
files:
  - source: /public_html/
    destination: /opt/deploy/
  - source: /config/
    destination: /opt/deploy/config
hooks:
  BeforeInstall:
    - location: build/scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: build/scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: build/scripts/deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: build/scripts/start_server.sh
      timeout: 300
      runas: root
